name: Code Quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  code_quality:
    uses: mruoss/action_elixir_run_tests/.github/workflows/elixir-code-quality.yml@v2.0.0
    with:
      checkout: true
      with-kubernetes: true
      check-formatting: true
      run-credo: strict
      run-dialyzer: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
